### ISSUE TITLE
add `ignore_existing` flag to MVG (or some methods in it)

### ISSUE THREAD

**Issue by aliaghelmaleki** [vikinganalytics/mvg#4]

**Comment by tuix** [comment]
Methods handling creation of sources and measurements would fail if sources with the identical name or measurements with identical source ID and timestamp already exist. This is intended in most cases but when the user wants to experiment (for instance using the examples in the documentation page) these calls need to be skipped. It can help to set `ignore_existing` flag in call to these methods so that the script can rerun without modification.

**Comment by tuix** [comment]
wait for #5. It is better to support this in `MVG` not in `MVGAPI`
